#######################################################
# This file belongs to the core repository.
# If your project repository is a fork of core,
# you are suggested to keep this file untouched in your project.
# This helps avoid merge conflicts when syncing from core.
#######################################################

fp32_matmul_precision: "high" # or highest, medium
dynamo_cache_size_limit: null
compile: true
precision: "bf16-mixed" # https://lightning.ai/docs/pytorch/stable/common/trainer.html#precision
sdpa: ["efficient"]
