#######################################################
# This file belongs to the core repository.
# If your project repository is a fork of core,
# you are suggested to keep this file untouched in your project.
# This helps avoid merge conflicts when syncing from core.
#######################################################

# https://mlflow.org

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  # experiment_name: ""
  # run_name: ""
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
  # run_id: ""
