#######################################################
# This file belongs to the core repository.
# If your project repository is a fork of core,
# you are suggested to keep this file untouched in your project.
# This helps avoid merge conflicts when syncing from core.
#######################################################

viz_rollout_1d:
  _target_: src.callbacks.viz_rollout_1d.VizRollout1D
  dirpath: ${paths.output_dir}/viz_rollout_1d
  valid_batches_local: "[0]"
  valid_batches_log: "[0]"
  test_batches_local: "[0]"
  test_batches_log: "[0]"
